require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Pasien2sController do

  # This should return the minimal set of attributes required to create a valid
  # Pasien2. As you add validations to Pasien2, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id_pasien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Pasien2sController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pasien2s as @pasien2s" do
      pasien2 = Pasien2.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pasien2s).should eq([pasien2])
    end
  end

  describe "GET show" do
    it "assigns the requested pasien2 as @pasien2" do
      pasien2 = Pasien2.create! valid_attributes
      get :show, {:id => pasien2.to_param}, valid_session
      assigns(:pasien2).should eq(pasien2)
    end
  end

  describe "GET new" do
    it "assigns a new pasien2 as @pasien2" do
      get :new, {}, valid_session
      assigns(:pasien2).should be_a_new(Pasien2)
    end
  end

  describe "GET edit" do
    it "assigns the requested pasien2 as @pasien2" do
      pasien2 = Pasien2.create! valid_attributes
      get :edit, {:id => pasien2.to_param}, valid_session
      assigns(:pasien2).should eq(pasien2)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pasien2" do
        expect {
          post :create, {:pasien2 => valid_attributes}, valid_session
        }.to change(Pasien2, :count).by(1)
      end

      it "assigns a newly created pasien2 as @pasien2" do
        post :create, {:pasien2 => valid_attributes}, valid_session
        assigns(:pasien2).should be_a(Pasien2)
        assigns(:pasien2).should be_persisted
      end

      it "redirects to the created pasien2" do
        post :create, {:pasien2 => valid_attributes}, valid_session
        response.should redirect_to(Pasien2.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pasien2 as @pasien2" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien2.any_instance.stub(:save).and_return(false)
        post :create, {:pasien2 => { "id_pasien" => "invalid value" }}, valid_session
        assigns(:pasien2).should be_a_new(Pasien2)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien2.any_instance.stub(:save).and_return(false)
        post :create, {:pasien2 => { "id_pasien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pasien2" do
        pasien2 = Pasien2.create! valid_attributes
        # Assuming there are no other pasien2s in the database, this
        # specifies that the Pasien2 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pasien2.any_instance.should_receive(:update_attributes).with({ "id_pasien" => "MyString" })
        put :update, {:id => pasien2.to_param, :pasien2 => { "id_pasien" => "MyString" }}, valid_session
      end

      it "assigns the requested pasien2 as @pasien2" do
        pasien2 = Pasien2.create! valid_attributes
        put :update, {:id => pasien2.to_param, :pasien2 => valid_attributes}, valid_session
        assigns(:pasien2).should eq(pasien2)
      end

      it "redirects to the pasien2" do
        pasien2 = Pasien2.create! valid_attributes
        put :update, {:id => pasien2.to_param, :pasien2 => valid_attributes}, valid_session
        response.should redirect_to(pasien2)
      end
    end

    describe "with invalid params" do
      it "assigns the pasien2 as @pasien2" do
        pasien2 = Pasien2.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien2.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien2.to_param, :pasien2 => { "id_pasien" => "invalid value" }}, valid_session
        assigns(:pasien2).should eq(pasien2)
      end

      it "re-renders the 'edit' template" do
        pasien2 = Pasien2.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien2.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien2.to_param, :pasien2 => { "id_pasien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pasien2" do
      pasien2 = Pasien2.create! valid_attributes
      expect {
        delete :destroy, {:id => pasien2.to_param}, valid_session
      }.to change(Pasien2, :count).by(-1)
    end

    it "redirects to the pasien2s list" do
      pasien2 = Pasien2.create! valid_attributes
      delete :destroy, {:id => pasien2.to_param}, valid_session
      response.should redirect_to(pasien2s_url)
    end
  end

end
