require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PasiensController do

  # This should return the minimal set of attributes required to create a valid
  # Pasien. As you add validations to Pasien, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "IdPasien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PasiensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pasiens as @pasiens" do
      pasien = Pasien.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pasiens).should eq([pasien])
    end
  end

  describe "GET show" do
    it "assigns the requested pasien as @pasien" do
      pasien = Pasien.create! valid_attributes
      get :show, {:id => pasien.to_param}, valid_session
      assigns(:pasien).should eq(pasien)
    end
  end

  describe "GET new" do
    it "assigns a new pasien as @pasien" do
      get :new, {}, valid_session
      assigns(:pasien).should be_a_new(Pasien)
    end
  end

  describe "GET edit" do
    it "assigns the requested pasien as @pasien" do
      pasien = Pasien.create! valid_attributes
      get :edit, {:id => pasien.to_param}, valid_session
      assigns(:pasien).should eq(pasien)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pasien" do
        expect {
          post :create, {:pasien => valid_attributes}, valid_session
        }.to change(Pasien, :count).by(1)
      end

      it "assigns a newly created pasien as @pasien" do
        post :create, {:pasien => valid_attributes}, valid_session
        assigns(:pasien).should be_a(Pasien)
        assigns(:pasien).should be_persisted
      end

      it "redirects to the created pasien" do
        post :create, {:pasien => valid_attributes}, valid_session
        response.should redirect_to(Pasien.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pasien as @pasien" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien.any_instance.stub(:save).and_return(false)
        post :create, {:pasien => { "IdPasien" => "invalid value" }}, valid_session
        assigns(:pasien).should be_a_new(Pasien)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien.any_instance.stub(:save).and_return(false)
        post :create, {:pasien => { "IdPasien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pasien" do
        pasien = Pasien.create! valid_attributes
        # Assuming there are no other pasiens in the database, this
        # specifies that the Pasien created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pasien.any_instance.should_receive(:update_attributes).with({ "IdPasien" => "MyString" })
        put :update, {:id => pasien.to_param, :pasien => { "IdPasien" => "MyString" }}, valid_session
      end

      it "assigns the requested pasien as @pasien" do
        pasien = Pasien.create! valid_attributes
        put :update, {:id => pasien.to_param, :pasien => valid_attributes}, valid_session
        assigns(:pasien).should eq(pasien)
      end

      it "redirects to the pasien" do
        pasien = Pasien.create! valid_attributes
        put :update, {:id => pasien.to_param, :pasien => valid_attributes}, valid_session
        response.should redirect_to(pasien)
      end
    end

    describe "with invalid params" do
      it "assigns the pasien as @pasien" do
        pasien = Pasien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien.to_param, :pasien => { "IdPasien" => "invalid value" }}, valid_session
        assigns(:pasien).should eq(pasien)
      end

      it "re-renders the 'edit' template" do
        pasien = Pasien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien.to_param, :pasien => { "IdPasien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pasien" do
      pasien = Pasien.create! valid_attributes
      expect {
        delete :destroy, {:id => pasien.to_param}, valid_session
      }.to change(Pasien, :count).by(-1)
    end

    it "redirects to the pasiens list" do
      pasien = Pasien.create! valid_attributes
      delete :destroy, {:id => pasien.to_param}, valid_session
      response.should redirect_to(pasiens_url)
    end
  end

end
