require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Pasien3sController do

  # This should return the minimal set of attributes required to create a valid
  # Pasien3. As you add validations to Pasien3, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "id_pasien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Pasien3sController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pasien3s as @pasien3s" do
      pasien3 = Pasien3.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pasien3s).should eq([pasien3])
    end
  end

  describe "GET show" do
    it "assigns the requested pasien3 as @pasien3" do
      pasien3 = Pasien3.create! valid_attributes
      get :show, {:id => pasien3.to_param}, valid_session
      assigns(:pasien3).should eq(pasien3)
    end
  end

  describe "GET new" do
    it "assigns a new pasien3 as @pasien3" do
      get :new, {}, valid_session
      assigns(:pasien3).should be_a_new(Pasien3)
    end
  end

  describe "GET edit" do
    it "assigns the requested pasien3 as @pasien3" do
      pasien3 = Pasien3.create! valid_attributes
      get :edit, {:id => pasien3.to_param}, valid_session
      assigns(:pasien3).should eq(pasien3)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pasien3" do
        expect {
          post :create, {:pasien3 => valid_attributes}, valid_session
        }.to change(Pasien3, :count).by(1)
      end

      it "assigns a newly created pasien3 as @pasien3" do
        post :create, {:pasien3 => valid_attributes}, valid_session
        assigns(:pasien3).should be_a(Pasien3)
        assigns(:pasien3).should be_persisted
      end

      it "redirects to the created pasien3" do
        post :create, {:pasien3 => valid_attributes}, valid_session
        response.should redirect_to(Pasien3.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pasien3 as @pasien3" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien3.any_instance.stub(:save).and_return(false)
        post :create, {:pasien3 => { "id_pasien" => "invalid value" }}, valid_session
        assigns(:pasien3).should be_a_new(Pasien3)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien3.any_instance.stub(:save).and_return(false)
        post :create, {:pasien3 => { "id_pasien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pasien3" do
        pasien3 = Pasien3.create! valid_attributes
        # Assuming there are no other pasien3s in the database, this
        # specifies that the Pasien3 created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pasien3.any_instance.should_receive(:update_attributes).with({ "id_pasien" => "MyString" })
        put :update, {:id => pasien3.to_param, :pasien3 => { "id_pasien" => "MyString" }}, valid_session
      end

      it "assigns the requested pasien3 as @pasien3" do
        pasien3 = Pasien3.create! valid_attributes
        put :update, {:id => pasien3.to_param, :pasien3 => valid_attributes}, valid_session
        assigns(:pasien3).should eq(pasien3)
      end

      it "redirects to the pasien3" do
        pasien3 = Pasien3.create! valid_attributes
        put :update, {:id => pasien3.to_param, :pasien3 => valid_attributes}, valid_session
        response.should redirect_to(pasien3)
      end
    end

    describe "with invalid params" do
      it "assigns the pasien3 as @pasien3" do
        pasien3 = Pasien3.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien3.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien3.to_param, :pasien3 => { "id_pasien" => "invalid value" }}, valid_session
        assigns(:pasien3).should eq(pasien3)
      end

      it "re-renders the 'edit' template" do
        pasien3 = Pasien3.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pasien3.any_instance.stub(:save).and_return(false)
        put :update, {:id => pasien3.to_param, :pasien3 => { "id_pasien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pasien3" do
      pasien3 = Pasien3.create! valid_attributes
      expect {
        delete :destroy, {:id => pasien3.to_param}, valid_session
      }.to change(Pasien3, :count).by(-1)
    end

    it "redirects to the pasien3s list" do
      pasien3 = Pasien3.create! valid_attributes
      delete :destroy, {:id => pasien3.to_param}, valid_session
      response.should redirect_to(pasien3s_url)
    end
  end

end
